<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7ncefcl\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7ncefcl/appProdProjectContainer.php') {
    touch(__DIR__.'/Container7ncefcl.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container7ncefcl\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container7ncefcl\appProdProjectContainer(array(
    'container.build_hash' => '7ncefcl',
    'container.build_id' => '157babf4',
    'container.build_time' => 1535958742,
), __DIR__.\DIRECTORY_SEPARATOR.'Container7ncefcl');
