<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHagasut\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHagasut/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerHagasut.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerHagasut\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerHagasut\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Hagasut',
    'container.build_id' => '6f9bfa28',
    'container.build_time' => 1539862310,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerHagasut');
